"use client"

import "@/components/pdf/pdf-worker"

import { WarningCircleIcon } from "@phosphor-icons/react"
import { useMemo, useState } from "react"
import { Document, Page } from "react-pdf"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Skeleton } from "@/components/ui/skeleton"
import { useElementWidth } from "@/hooks/use-element-width"

export type PdfViewerProps = {
  /** Original file or generated bytes (e.g. the V2 Custom preview). */
  source: File | Uint8Array
  className?: string
}

/** Renders every page of a PDF, scaled to the container width. */
export default function PdfViewerImpl({ source, className }: PdfViewerProps) {
  const { ref, width } = useElementWidth<HTMLDivElement>()
  const [numPages, setNumPages] = useState(0)

  // pdf.js transfers the buffer to its worker, so hand it a private copy.
  const file = useMemo(
    () => (source instanceof Uint8Array ? { data: source.slice() } : source),
    [source],
  )

  return (
    <div ref={ref} className={className}>
      {width > 0 && (
        <Document
          file={file}
          onLoadSuccess={({ numPages: total }) => setNumPages(total)}
          loading={<Skeleton className="aspect-[1/1.414] w-full" />}
          error={
            <Alert variant="destructive">
              <WarningCircleIcon />
              <AlertTitle>PDF tidak dapat ditampilkan</AlertTitle>
              <AlertDescription>File mungkin rusak atau terproteksi.</AlertDescription>
            </Alert>
          }
        >
          <div className="space-y-4">
            {Array.from({ length: numPages }, (_, index) => (
              <div key={index} className="space-y-1">
                <Page
                  pageNumber={index + 1}
                  width={width}
                  renderTextLayer={false}
                  renderAnnotationLayer={false}
                  className="overflow-hidden rounded-md border bg-white shadow-sm"
                  loading={<Skeleton className="aspect-[1/1.414] w-full" />}
                />
                <p className="text-muted-foreground text-center text-xs">
                  Halaman {index + 1} / {numPages}
                </p>
              </div>
            ))}
          </div>
        </Document>
      )}
    </div>
  )
}
